apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: aws_ebs-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-06af7d3c9efdafacf
    fsType: xfs 

