apiVersion: v1
kind: Pod 
metadata:
  name: secret-pod
spec: 
  containers:
  - name: busybox
    image: busybox
    command: [ "/bin/sh" ]
    args: [ "-c", "sleep 600" ]
    volumeMounts:
    - name: generic-mount 
      mountPath: /environment_var
  volumes:
    name: generic-mount
    secret:
      secretName: demotest 
        
